apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cmd_server_name }}
  labels:
    dev-room: {{ .Values.cmd_server_name }}
spec:
  ports:
    - port: {{ .Values.web_service_port }}
      targetPort: 80
  selector:
    app: {{ .Values.cmd_server_name }}
  type: {{ .Values.service_type }}