apiVersion: v1
kind: ConfigMap
metadata:
  name: student-{{ .Values.test_student_id }}-{{ .Values.test_class_id | lower }}-config
  labels:
    student_id: id-{{ .Values.test_student_id }}
    class_id: id-{{ .Values.test_class_id }}
data:
  # 전체 스크립트 관리
  init.sh: |-
    #!/bin/bash

    script_dir=$(dirname "$0")
    echo "스크립트 폴더: $script_dir"

    for script_file in "$script_dir"/*.sh; do
        # 현재 실행 중인 스크립트와 같은 파일이 아닌 경우에만 실행
        if [ "$script_file" != "$0" ]; then
            echo "실행 스크립트 파일: $script_file"
            bash "$script_file" >> /script/log
            echo "---------------------------------------"
        fi
    done

  # ssh 설치용 스크립트
  01_init_ssh.sh: |-
    #!/bin/bash
    
    mkdir ~/hello

    # 패키지 업데이트 및 필요 패키지 설치
    apt update
    apt install -y sudo
    apt install -y openssh-server

    # 새로운 사용자 생성
    student_id={{ .Values.test_student_id }}
    class_id={{ .Values.test_class_id | lower }}
    username="$student_id"-"$class_id"
    useradd -m "$username"
    echo "$username:test" | chpasswd
    usermod -aG sudo "$username"

    # 볼륨 권한 설정
    student_folder_path="{{ .Values.student_mount_path }}/{{ .Values.test_student_id }}-{{ .Values.test_class_id | lower }}"
    echo "$student_folder_path"
    chmod -R 777 "$student_folder_path"

    # SSH 서버 실행
    service ssh start
    

