{{- range $pv:= .Values.pv_group }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $pv.name }}-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ $.Values.pv_capacity }}
  volumeName: {{ $pv.name }}
  storageClassName: ""
{{- end }}